//Sensors
#define SENSOR_RIDER_EFFORT 0
#define SENSOR_CURRENT_STRAIN 1
#define SENSOR_SPEED 2
#define SENSOR_RAW_STRAIN 3
#define SENSOR_TORQUE_APPLIED 4
#define SENSOR_MOTOR_TEMP 5
#define SENSOR_BATTERY_VOLTAGE 6
#define SENSOR_FILTERED_RIDER_EFFORT 7

#define NUM_SENSORS 8 //Is there a better way to do this?

//Properties
#define PROPERTY_SMOOTHING_MIN 0
#define PROPERTY_SMOOTHING_MAX 1
#define PROPERTY_STROKE_TIMEOUT_CYCLES 2
#define PROPERTY_MAX_EFFORT 3
#define PROPERTY_TORQUE_MULTIPLIER 4
#define PROPERTY_SENSOR_RIDER_EFFORT_STATE 5
#define PROPERTY_SENSOR_CURRENT_STRAIN_STATE 6
#define PROPERTY_SENSOR_SPEED_STATE 7
#define PROPERTY_SENSOR_RAW_STRAIN_STATE 8
#define PROPERTY_SENSOR_TORQUE_APPLIED_STATE 9
#define PROPERTY_SENSOR_MOTOR_TEMP_STATE 10
#define PROPERTY_SENSOR_BATTERY_VOLTAGE_STATE 11
#define PROPERTY_MAX_SPEED 12
#define PROPERTY_RIDER_EFFORT_FILTER_STRENGTH 13
#define PROPERTY_SENSOR_FILTERED_RIDER_EFFORT_STATE 14
#define PROPERTY_FANCY_ASSIST_STATE 15

#define NUM_PROPERTIES 16 //Is there a better way to do this?

//Request Identifiers
#define REQUEST_CONNECT 10
#define REQUEST_DISCONNECT 11
#define REQUEST_GET_PROPERTY_VALUE 12
#define REQUEST_SET_PROPERTY_VALUE 13
#define REQUEST_ADD_BEZIER 14
#define REQUEST_GET_SENSOR_VALUE 15
#define REQUEST_WRITE_PROPERTY 16
#define REQUEST_WRITE_BEZIER 17
#define REQUEST_WRITE_GET_PROPERTY 18
