//Sensors
#define SENSOR_RIDER_EFFORT 0
#define SENSOR_CURRENT_STRAIN 1
#define SENSOR_SPEED 2
#define SENSOR_RAW_STRAIN 3
#define SENSOR_TORQUE_APPLIED 4
#define SENSOR_MOTOR_TEMP 5
#define SENSOR_BATTERY_VOLTAGE 6

#define NUM_SENSORS 7 //Is there a better way to do this?

//Properties
#define PROPERTY_SMOOTHING_MIN 0
#define PROPERTY_SMOOTHING_MAX 1
#define PROPERTY_MAX_OUTPUT 2
#define PROPERTY_STROKE_TIMEOUT_CYCLES 3
#define PROPERTY_MAX_EFFORT 4
#define PROPERTY_TORQUE_MULTIPLIER 5
#define PROPERTY_MAX_STRAIN_DAMPING_SPEED 6
#define PROPERTY_STRAIN_DAMPING_CONTROL1_X 7
#define PROPERTY_STRAIN_DAMPING_CONTROL1_Y 8
#define PROPERTY_STRAIN_DAMPING_CONTROL2_X 9
#define PROPERTY_STRAIN_DAMPING_CONTROL2_Y 10
#define PROPERTY_SENSOR_RIDER_EFFORT_STATE 11
#define PROPERTY_SENSOR_CURRENT_STRAIN_STATE 12
#define PROPERTY_SENSOR_SPEED_STATE 13
#define PROPERTY_SENSOR_RAW_STRAIN_STATE 14
#define PROPERTY_SENSOR_TORQUE_APPLIED_STATE 15
#define PROPERTY_SENSOR_MOTOR_TEMP_STATE 16
#define PROPERTY_SENSOR_BATTERY_VOLTAGE_STATE 17

#define NUM_PROPERTIES 18 //Is there a better way to do this?

//Used to sync iOS to Arduino
#define SEND_PARAMS_BYTE 0xEE
#define DISCONNECT_BYTE 0xFF

#define FIRST_PROPERTY_IDENTIFIER 0
#define FIRST_SENSOR_IDENTIFIER 150
#define FIRST_EVENT_IDENTIFIER 175
#define FIRST_COMMAND_IDENTIFIER 200
