#define EEP_SMOOTHING_MIN_MSB   0
#define EEP_SMOOTHING_MIN_LSB   1
#define EEP_SMOOTHING_MAX_MSB   2
#define EEP_SMOOTHING_MAX_LSB   3
#define EEP_MAX_OUTPUT_MSB      4
#define EEP_MAX_OUTPUT_LSB      5
#define EEP_MAXSTRAINDAMP_MSB   6
#define EEP_MAXSTRAINDAMP_LSB   7
#define EEP_STRAINDAMPCURVE_MSB 8
#define EEP_STRAINDAMPCURVE_LSB 9
#define EEP_STROKETIMOUTCYC_MSB 10 
#define EEP_STROKETIMOUTCYC_LSB 11 
#define EEP_MAXEFFORT_MSB       12
#define EEP_MAXEFFORT_LSB       13
#define EEP_TRQ_MULT_MSB        14
#define EEP_TRQ_MULT_LSB        15



