//IO PIN DEFINITIONS
#define CAN_READY_PIN 2
#define SWITCH_LED_PIN 4
#define ON_OFF_SWITCH_PIN 5
#define INDICATOR_LED_PIN 6
#define BLE_POWER_PIN 7

//Vehicle State
#define VEHICLE_OFF 0
#define VEHICLE_ON 1

//Constants for configuration of the strain characterization algorithm
#define STANDARD_ASSIST 0
#define THREE_DIMENSIONAL_MAPPING 1
#define EFFORT_MAPPING 2

//Bezier Curves
#define CURVE_TYPE_ASSIST 0
#define CURVE_TYPE_DAMPING 1

#define NUM_BEZIERS 2

//Sensors
#define SENSOR_RIDER_EFFORT 0
#define SENSOR_CURRENT_STRAIN 1
#define SENSOR_SPEED 2
#define SENSOR_RAW_STRAIN 3
#define SENSOR_TORQUE_APPLIED 4
#define SENSOR_MOTOR_TEMP 5
#define SENSOR_BATTERY_VOLTAGE 6
#define SENSOR_FILTERED_RIDER_EFFORT 7

#define NUM_SENSORS 8 //Is there a better way to do this?

//Properties
#define PROPERTY_SMOOTHING_MIN 0
#define PROPERTY_SMOOTHING_MAX 1
#define PROPERTY_STROKE_TIMEOUT_CYCLES 2
#define PROPERTY_MAX_EFFORT 3
#define PROPERTY_TORQUE_MULTIPLIER 4
#define PROPERTY_SENSOR_RIDER_EFFORT_STATE 5
#define PROPERTY_SENSOR_CURRENT_STRAIN_STATE 6
#define PROPERTY_SENSOR_SPEED_STATE 7
#define PROPERTY_SENSOR_RAW_STRAIN_STATE 8
#define PROPERTY_SENSOR_TORQUE_APPLIED_STATE 9
#define PROPERTY_SENSOR_MOTOR_TEMP_STATE 10
#define PROPERTY_SENSOR_BATTERY_VOLTAGE_STATE 11
#define PROPERTY_RIDER_EFFORT_FILTER_STRENGTH 12
#define PROPERTY_SENSOR_FILTERED_RIDER_EFFORT_STATE 13
#define PROPERTY_FANCY_ASSIST_STATE 14
#define PROPERTY_NUM_PROPERTIES 15

#define NUM_PROPERTIES 16 //Is there a better way to do this?

//Helpful
#define UINT16_MAX 65535
#define BYTE_MAX 255
